version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pipelineiq-db
    environment:
      POSTGRES_USER: pipelineiq
      POSTGRES_PASSWORD: pipelineiq
      POSTGRES_DB: pipelineiq
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
